Fixes weird, possibly Poltergeist-only bug
The `bind` call seems to be unneeded and it's causing `TypeError: 'undefined' is not a function (near '...}.bind($this), 150);...')` errors. Removing it seems to resolve them.